### ISSUE TITLE
Doesn't work with C18?

### ISSUE THREAD

**Issue by BloodyRain2k** [MKleinSB/pxt-dht11#2]
I'm not sure if I've found a technical limitation of the v2.0 Mini, but I've been struggling with getting a simple DHT11 sensor working with my v2.0 Mini for the last couple days.

It took until *now* for me to just try a different port than C18 (which I purely picked because of proximity to the 3V and GND ports literally next to it) and bam! My script that just cause the Mini to hang instantly worked.

The script in question is here, https://makecode.calliope.cc/_hWfJqt8tMY2i and I've tested that version which uses C17 if A is pressed and C18 if B is pressed.

As intented, if A is pressed (and the sensor is appropriately connected) the matrix shows the humidity, by showing an amount of dots on either side representing the digit. In my case, 51 = 5 dots on the left and 1 on the right.
However, when wired up to C18 and pressing B, nothing happens.

Similarily, when pressing A before connecting the sensor, it won't work either *after* connecting it appropriately. So it seems that on top of not working with C18, it also hangs the Mini if a reading attempt failed.

Since I'm fairly new to using the Mini for anying, it might be that this is a known hardware issue, but in case it isn't I wanted to point it out.

**Comment by MKleinSB** [comment]
Hallo BloodyRain2k,
der linke Groveport (mit C18) ist der I2C-Port. D.h. der ist eigentlich nicht für andere digitale Signale außer I2C gedacht. Calliope hat C18 nur für den Lichtsensor seines Motionkit freigegeben. Da ist es nicht kritisch wenn mal ein Signal verschluckt wird oder Fremdsignale kommen.
Der DHT11 ist aber kritisch bei Fremdsignalen, deswegen funktioniert er nicht richtig.

Viel Spaß mit dem Calliope

Michael

PS: hier gibt es noch weitere Projekte

[https://www.hackster.io/MKlein](https://www.hackster.io/MKlein)
